// ALPVersion.h
// ARGOS Landing Pad version control
// ------------------------------------------------------------------------------------------------
// This file is automatically generated from the build and source control environment.
//
///////////////////////////////////////////////////////////////////////////////////////////////////

#ifndef __ALPVERSION_H__
#define __ALPVERSION_H__

#define ALP_VERSION_MAJOR   1
#define ALP_VERSION_MINOR   0
#define ALP_VERSION_BLDHI   0
#define ALP_VERSION_BLDLW   0

#endif